### ISSUE TITLE
Update the CSS and muted icon

### ISSUE THREAD

**Issue by Umcaruje** [HDDigitizerMusic/lmms-alt-theme#20]
@RebeccaDeField now that my TCO refactoring is finished, I just wanted to note you on some CSS changes for the TCO's
- The vast majority of the properties has been consolidated into one block that applies to all patterns:

``` css
TrackContentObjectView   {
    qproperty-mutedColor: rgb( 128, 128, 128 );
    qproperty-mutedBackgroundColor: rgb( 80, 80, 80 );
    qproperty-selectedColor: rgb( 0, 125, 255 );
    qproperty-textColor: rgb( 255, 255, 255 );
    qproperty-textShadowColor: rgb( 0, 0, 0 );
    qproperty-gradient: true;
}
```
- `color` of the TCO's is now `background-color` and `qproperty-fgColor` is now `color`.
- the 'muted' pixmap is now displayed as 14x14, so it doesn't clash with the text. It'd be good if you redesigned it to be pixel perfect :)

If I think of any new CSS changes, I'll post more comments to this issue.

**Comment by RebeccaDeField** [comment]
Perfect, this is way more organized and simplified! Thank you for the info. I will let you know if I have any questions.

**Comment by Umcaruje** [comment]
Ok, so I'll go under CSS changes by PR's: 
- https://github.com/LMMS/lmms/pull/2554 added 

``` css
qproperty-crossColor: rgb( 255, 51, 51 );
```

to `AutomationEditor` and 

``` css
qproperty-selectedNoteColor: rgb( 0, 64, 192 );
qproperty-markedSemitoneColor: rgba( 40, 40, 40, 200 );
/* Text on the white piano keys */
qproperty-textColor: rgb( 0, 0, 0 );
qproperty-textColorLight: rgb( 128, 128, 128);
qproperty-textShadow: rgb( 240, 240, 240 );
```

to `PianoRoll`
- https://github.com/LMMS/lmms/pull/2547 added 

``` css
qproperty-strokeOuterActive: rgb( 0, 0, 0 );    
qproperty-strokeOuterInactive: rgba( 0, 0, 0, 50 ); 
qproperty-strokeInnerActive: rgba( 255, 255, 255, 100 );    
qproperty-strokeInnerInactive: rgba( 255, 255, 255, 50 );   
```

to `FXLine`
- https://github.com/LMMS/lmms/pull/2547 added a whole new section:

``` css

/* Instrument plugin list */

PluginDescList {
    background-color: #5b6571;
}

PluginDescWidget {
    background-color: #e0e0e0;
    color: #404040;
    border: 1px solid rgb(64, 64, 64);
    margin: 0px;
}

PluginDescWidget:hover {
    background-color: #e0e0e0;
}

```
- https://github.com/LMMS/lmms/pull/2540 added 

``` css
qproperty-noteBorderRadiusX: 5;
qproperty-noteBorderRadiusY: 2;
```

to `PianoRoll`

Please note that all of these'll need to be added to your stylesheet, otherwise they'll stay black, which is their initialization value.
